/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;
public class Author_login extends javax.swing.JFrame {

    Connection con;
    PreparedStatement p;
    ResultSet r;
    public Author_login() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");  
            
        }catch(Exception e){
             
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablealldata = new javax.swing.JTable();
        booklistshow = new javax.swing.JButton();
        booklisthide = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Book_name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Book_Author = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Book_Edition = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Book_status = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Book_quantity = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Book_Department = new javax.swing.JTextField();
        jButton_registationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 209), 2));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setBackground(new java.awt.Color(204, 51, 0));
        jLabel8.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 209));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Book List");

        jSeparator2.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator2.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator2.setOpaque(true);

        tablealldata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablealldata.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tablealldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "boook_name", "Author", "Edition", "Status", "Quantity", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablealldata.setCellSelectionEnabled(true);
        tablealldata.setMinimumSize(new java.awt.Dimension(90, 90));
        tablealldata.setRowHeight(30);
        jScrollPane1.setViewportView(tablealldata);

        booklistshow.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        booklistshow.setForeground(new java.awt.Color(0, 204, 209));
        booklistshow.setText("Show");
        booklistshow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        booklistshow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        booklistshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booklistshowActionPerformed(evt);
            }
        });

        booklisthide.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        booklisthide.setForeground(new java.awt.Color(0, 204, 209));
        booklisthide.setText("Hide");
        booklisthide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        booklisthide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        booklisthide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booklisthideActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 209));

        searchText.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        searchText.setForeground(new java.awt.Color(0, 204, 209));
        searchText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 209)));
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 209));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search Record");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Unispace", 2, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/backicon.png"))); // NOI18N
        jButton2.setText("Logout");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/search24.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator1.setOpaque(true);

        Book_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_name.setText("Book Name");
        Book_name.setBorder(null);
        Book_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_nameFocusLost(evt);
            }
        });
        Book_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_nameMouseClicked(evt);
            }
        });
        Book_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_nameActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator3.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 209));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Book List Add");

        jSeparator4.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator4.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator4.setOpaque(true);

        Book_Author.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_Author.setText("Author");
        Book_Author.setBorder(null);
        Book_Author.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_AuthorFocusLost(evt);
            }
        });
        Book_Author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_AuthorMouseClicked(evt);
            }
        });
        Book_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_AuthorActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator5.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator5.setOpaque(true);

        Book_Edition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_Edition.setText("Edition");
        Book_Edition.setBorder(null);
        Book_Edition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_EditionFocusLost(evt);
            }
        });
        Book_Edition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_EditionMouseClicked(evt);
            }
        });
        Book_Edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_EditionActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator6.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator6.setOpaque(true);

        Book_status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_status.setText("Status");
        Book_status.setBorder(null);
        Book_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_statusFocusLost(evt);
            }
        });
        Book_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_statusMouseClicked(evt);
            }
        });
        Book_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_statusActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator7.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator7.setOpaque(true);

        Book_quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_quantity.setText("Quantity");
        Book_quantity.setBorder(null);
        Book_quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_quantityFocusLost(evt);
            }
        });
        Book_quantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_quantityMouseClicked(evt);
            }
        });
        Book_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_quantityActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator8.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator8.setOpaque(true);

        Book_Department.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_Department.setText("Department");
        Book_Department.setBorder(null);
        Book_Department.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_DepartmentFocusLost(evt);
            }
        });
        Book_Department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_DepartmentMouseClicked(evt);
            }
        });
        Book_Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_DepartmentActionPerformed(evt);
            }
        });

        jButton_registationBtn.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jButton_registationBtn.setForeground(new java.awt.Color(0, 204, 209));
        jButton_registationBtn.setText("Add book");
        jButton_registationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_registationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(265, 265, 265)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator5)
                                            .addComponent(Book_Edition, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator6)
                                            .addComponent(Book_status, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator7)
                                            .addComponent(Book_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator8)
                                            .addComponent(Book_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator1)
                                            .addComponent(Book_name, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator4)
                                            .addComponent(Book_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(317, 317, 317)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(booklistshow, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(booklisthide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jButton_registationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addGap(282, 282, 282))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(booklistshow)
                    .addComponent(booklisthide))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Book_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Book_Edition, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Book_status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Book_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Book_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Book_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jButton_registationBtn)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void booklistshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booklistshowActionPerformed
        // TODO add your handling code here:
        String sql="SELECT * FROM book_list";

        try{
             p=con.prepareStatement(sql);
             r= p.executeQuery();
            DefaultTableModel model=(DefaultTableModel)tablealldata.getModel();
            model.setRowCount(0);

            while(r.next()){
                model.addRow(new String[]{ r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)});
            }
        }
        catch(Exception e){System.out.println("eroor"+ e.getMessage());}

    }//GEN-LAST:event_booklistshowActionPerformed

     public void forsearch(String str){
      DefaultTableModel  model=(DefaultTableModel)tablealldata.getModel();
      TableRowSorter<DefaultTableModel> tablesorter= new TableRowSorter<>(model);
      tablealldata.setRowSorter(tablesorter);
      tablesorter.setRowFilter(RowFilter.regexFilter(str));
    }
    
    
    private void booklisthideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booklisthideActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)tablealldata.getModel();
        model.setRowCount(0);
        model.setRowCount(5);

    }//GEN-LAST:event_booklisthideActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        // TODO add your handling code here:
        String searchString=searchText.getText();
        forsearch(searchString);
    }//GEN-LAST:event_searchTextKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Book_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_nameFocusLost
        // TODO add your handling code here:
        String uservalue = Book_name.getText().trim().toLowerCase();
        if(uservalue.equals("book name") || uservalue.equals("") )
        {
            Book_name.setText("Book Name");
        }
    }//GEN-LAST:event_Book_nameFocusLost

    private void Book_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_nameMouseClicked
        // TODO add your handling code here:
        String uservalue = Book_name.getText().trim().toLowerCase();
        if(uservalue.equals("book name") || uservalue.equals("") )
        {
            Book_name.setText("");
        }
    }//GEN-LAST:event_Book_nameMouseClicked

    private void Book_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_nameActionPerformed

    private void Book_AuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_AuthorFocusLost
       String uservalue = Book_Author.getText().trim().toLowerCase();
        if(uservalue.equals("author") || uservalue.equals("") )
        {
            Book_Author.setText("Author");
        }
    }//GEN-LAST:event_Book_AuthorFocusLost

    private void Book_AuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_AuthorMouseClicked
        
        String uservalue = Book_Author.getText().trim().toLowerCase();
        if(uservalue.equals("author") || uservalue.equals("") )
        {
            Book_Author.setText("");
        }
        
    }//GEN-LAST:event_Book_AuthorMouseClicked

    private void Book_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_AuthorActionPerformed

    private void Book_EditionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_EditionFocusLost
        
        String uservalue = Book_Edition.getText().trim().toLowerCase();
        if(uservalue.equals("edition") || uservalue.equals("") )
        {
            Book_Edition.setText("Edition");
        }
        
        
    }//GEN-LAST:event_Book_EditionFocusLost

    private void Book_EditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_EditionMouseClicked
        
        String uservalue = Book_Edition.getText().trim().toLowerCase();
        if(uservalue.equals("edition") || uservalue.equals("") )
        {
            Book_Edition.setText("");
        }
        
    }//GEN-LAST:event_Book_EditionMouseClicked

    private void Book_EditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_EditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_EditionActionPerformed

    private void Book_statusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_statusFocusLost
         String uservalue = Book_status.getText().trim().toLowerCase();
        if(uservalue.equals("status") || uservalue.equals("") )
        {
            Book_status.setText("Status");
        }
    }//GEN-LAST:event_Book_statusFocusLost

    private void Book_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_statusMouseClicked
        
         String uservalue = Book_status.getText().trim().toLowerCase();
        if(uservalue.equals("status") || uservalue.equals("") )
        {
            Book_status.setText("");
        }
        
    }//GEN-LAST:event_Book_statusMouseClicked

    private void Book_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_statusActionPerformed

    private void Book_quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_quantityFocusLost
        
         String uservalue = Book_quantity.getText().trim().toLowerCase();
        if(uservalue.equals("quantity") || uservalue.equals("") )
        {
            Book_quantity.setText("Quantity");
        }
    }//GEN-LAST:event_Book_quantityFocusLost

    private void Book_quantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_quantityMouseClicked
       
         String uservalue = Book_quantity.getText().trim().toLowerCase();
        if(uservalue.equals("quantity") || uservalue.equals("") )
        {
            Book_quantity.setText("");
        }
        
    }//GEN-LAST:event_Book_quantityMouseClicked

    private void Book_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_quantityActionPerformed

    private void Book_DepartmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_DepartmentFocusLost
        String uservalue = Book_Department.getText().trim().toLowerCase();
        if(uservalue.equals("department") || uservalue.equals("") )
        {
            Book_Department.setText("Department");
        }
    }//GEN-LAST:event_Book_DepartmentFocusLost

    private void Book_DepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_DepartmentMouseClicked
         String uservalue = Book_Department.getText().trim().toLowerCase();
        if(uservalue.equals("department") || uservalue.equals("") )
        {
            Book_Department.setText("");
        }
    }//GEN-LAST:event_Book_DepartmentMouseClicked

    private void Book_DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_DepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_DepartmentActionPerformed

    private void jButton_registationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registationBtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="INSERT INTO `book_list`(`boook_name`, `Author`, `Edition`, `Status`, `Quantity`, `Department`) VALUES (?,?,?,?,?,?)";
            p=con.prepareStatement(sql);
            p.setString(1, Book_name.getText());
            p.setString(2, Book_Author.getText());
            p.setString(3, Book_Edition.getText());
            p.setString(4, Book_status.getText());
            p.setString(5, Book_quantity.getText());
            p.setString(6, Book_Department.getText());
            p.executeUpdate();
            JOptionPane.showMessageDialog(this," Add book Succesfull" );
            
            Book_name.setText("Book Name");
            Book_Author.setText("Author"); 
            Book_Edition.setText("Edition");
            Book_status.setText("Status");
            Book_quantity.setText("Quantity");
            Book_Department.setText("Department");
            

        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton_registationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Author_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Author_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Author_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Author_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Author_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Book_Author;
    private javax.swing.JTextField Book_Department;
    private javax.swing.JTextField Book_Edition;
    private javax.swing.JTextField Book_name;
    private javax.swing.JTextField Book_quantity;
    private javax.swing.JTextField Book_status;
    private javax.swing.JButton booklisthide;
    private javax.swing.JButton booklistshow;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_registationBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField searchText;
    private javax.swing.JTable tablealldata;
    // End of variables declaration//GEN-END:variables
}
