/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management;
import java.sql.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

/**
 *
 * @author rkrakib
 */
public class LoginUser extends javax.swing.JFrame {
Connection con;
    PreparedStatement p,pp;
    ResultSet r;
    /**
     * Creates new form LoginAuthor
     */
    public LoginUser() {
        initComponents();
        afterloginstyle.setVisible(true);
        issuBookpanel.setVisible(false);
        booklistpanel.setVisible(false);
        returnBookpanel.setVisible(false);
       
       
        
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");  
             
            
        }catch(Exception e){
             
        }
        bookid1.setBackground(new java.awt.Color(0,0,0,5));
        userid2.setBackground(new java.awt.Color(0,0,0,5));
        issudate1.setBackground(new java.awt.Color(0,0,0,5));
        duedate1.setBackground(new java.awt.Color(0,0,0,5));
         returndateinput.setBackground(new java.awt.Color(0,0,0,5));
        bookid.setBackground(new java.awt.Color(0,0,0,5));
        bookid1.setBackground(new java.awt.Color(0,0,0,5));
        userid.setBackground(new java.awt.Color(0,0,0,5));
        issudate.setBackground(new java.awt.Color(0,0,0,5));
        duedate.setBackground(new java.awt.Color(0,0,0,5));
        
        jPanel13.setBackground(new java.awt.Color(0,0,0,40));
        jPanel14.setBackground(new java.awt.Color(0,0,0,40));
        issueBookbackground.setBackground(new java.awt.Color(0,0,0,180));
        //addbooklistpanel.setBackground(new java.awt.Color(0,0,0,3));
//        bookid.setBackground(new java.awt.Color(0,0,0,5));
//        userid.setBackground(new java.awt.Color(0,0,0,5));
//        issudate.setBackground(new java.awt.Color(0,0,0,5));
//        duedate.setBackground(new java.awt.Color(0,0,0,5));
       
        
        searchText.setBackground(new java.awt.Color(0,0,0,5));
        jPanel15.setBackground(new java.awt.Color(0,0,0,60));
        jPanel3.setBackground(new java.awt.Color(0,0,0,60));
        
       
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Booklist = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        deletBookbtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        afterloginstyle = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        booklistpanel = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablealldata = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton_registationBtn2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        issuBookpanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        duedate = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        bookid = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jButton_registationBtn = new javax.swing.JButton();
        issudate = new javax.swing.JTextField();
        issueBookbackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        returnBookpanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        bookid1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        userid2 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        issudate1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        duedate1 = new javax.swing.JTextField();
        returnbooksubmit = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        returndateinput = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(56, 151, 204));
        jPanel1.setForeground(new java.awt.Color(160, 147, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 204, 209));

        Booklist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Booklist.setForeground(new java.awt.Color(255, 255, 255));
        Booklist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/books-24.png"))); // NOI18N
        Booklist.setText("Book list");
        Booklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Booklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooklistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooklistMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Booklist, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(89, 89, 89))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Booklist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 204, 209));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginUserIcon/book-stack-24.png"))); // NOI18N
        jLabel2.setText("Issue Book");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 204, 209));

        deletBookbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletBookbtn.setForeground(new java.awt.Color(255, 255, 255));
        deletBookbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginUserIcon/arrow-85-24.png"))); // NOI18N
        deletBookbtn.setText("Return Book");
        deletBookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletBookbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletBookbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(deletBookbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletBookbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 253, -1));

        jLabel3.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Users");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 40));

        jPanel4.setBackground(new java.awt.Color(0, 204, 209));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/account-logout-16.png"))); // NOI18N
        jLabel10.setText("Logout");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 30));

        jLabel6.setBackground(new java.awt.Color(0, 204, 209));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/library-background1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(253, 335));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 2, -1, 460));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 460));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        afterloginstyle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 209));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("City University");
        jPanel15.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 350, 70));

        jLabel19.setBackground(new java.awt.Color(204, 51, 0));
        jLabel19.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, 30));

        afterloginstyle.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/cityuniversity.png"))); // NOI18N
        afterloginstyle.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        booklistpanel.setBackground(new java.awt.Color(204, 204, 204));
        booklistpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchText.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        searchText.setForeground(new java.awt.Color(255, 255, 255));
        searchText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 209)));
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });
        booklistpanel.add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, 30));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablealldata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablealldata.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tablealldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "boook_name", "Author", "Edition", "Status", "Quantity", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablealldata.setCellSelectionEnabled(true);
        tablealldata.setMinimumSize(new java.awt.Dimension(90, 90));
        tablealldata.setRowHeight(30);
        jScrollPane1.setViewportView(tablealldata);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 700, 260));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 209));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Search Record");
        jPanel14.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 140, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/search24.png"))); // NOI18N
        jPanel14.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 30, 50));

        jLabel14.setBackground(new java.awt.Color(204, 51, 0));
        jLabel14.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, -1));

        jButton_registationBtn2.setBackground(new java.awt.Color(255, 255, 255));
        jButton_registationBtn2.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jButton_registationBtn2.setForeground(new java.awt.Color(0, 204, 209));
        jButton_registationBtn2.setText("PDF BOOK");
        jButton_registationBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 209), 1, true));
        jButton_registationBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_registationBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registationBtn2ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton_registationBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 130, 30));

        booklistpanel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgImgAfterLogin/bg-afterLogin.jpg"))); // NOI18N
        booklistpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        issuBookpanel.setBackground(new java.awt.Color(51, 0, 102));
        issuBookpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(204, 51, 0));
        jLabel15.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        issuBookpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, -1));

        userid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userid.setText("User Id");
        userid.setBorder(null);
        userid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                useridFocusLost(evt);
            }
        });
        userid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                useridMouseClicked(evt);
            }
        });
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        issuBookpanel.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 180, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator9.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator9.setOpaque(true);
        issuBookpanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, -1));

        duedate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        duedate.setForeground(new java.awt.Color(255, 255, 255));
        duedate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duedate.setText("Due Date");
        duedate.setBorder(null);
        duedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                duedateFocusLost(evt);
            }
        });
        duedate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duedateMouseClicked(evt);
            }
        });
        duedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedateActionPerformed(evt);
            }
        });
        issuBookpanel.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 180, 30));

        jSeparator10.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator10.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator10.setOpaque(true);
        issuBookpanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 180, -1));

        bookid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookid.setForeground(new java.awt.Color(255, 255, 255));
        bookid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookid.setText("Book  Id");
        bookid.setBorder(null);
        bookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookidFocusLost(evt);
            }
        });
        bookid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookidMouseClicked(evt);
            }
        });
        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });
        issuBookpanel.add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, 30));

        jSeparator12.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator12.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator12.setOpaque(true);
        issuBookpanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, -1));

        jSeparator8.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator8.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator8.setOpaque(true);
        issuBookpanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 180, -1));

        jButton_registationBtn.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jButton_registationBtn.setForeground(new java.awt.Color(0, 204, 209));
        jButton_registationBtn.setText("Issue Book");
        jButton_registationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_registationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registationBtnActionPerformed(evt);
            }
        });
        issuBookpanel.add(jButton_registationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 140, -1));

        issudate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        issudate.setForeground(new java.awt.Color(255, 255, 255));
        issudate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        issudate.setText("Issue Date");
        issudate.setBorder(null);
        issudate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                issudateFocusLost(evt);
            }
        });
        issudate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issudateMouseClicked(evt);
            }
        });
        issudate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issudateActionPerformed(evt);
            }
        });
        issuBookpanel.add(issudate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 180, 30));

        javax.swing.GroupLayout issueBookbackgroundLayout = new javax.swing.GroupLayout(issueBookbackground);
        issueBookbackground.setLayout(issueBookbackgroundLayout);
        issueBookbackgroundLayout.setHorizontalGroup(
            issueBookbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        issueBookbackgroundLayout.setVerticalGroup(
            issueBookbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        issuBookpanel.add(issueBookbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 600, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/library2.jpg"))); // NOI18N
        issuBookpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        returnBookpanel.setBackground(new java.awt.Color(213, 239, 239));
        returnBookpanel.setPreferredSize(new java.awt.Dimension(720, 460));
        returnBookpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(204, 51, 0));
        jLabel16.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("X");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        returnBookpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, -1));

        jSeparator13.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator13.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator13.setOpaque(true);
        returnBookpanel.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        bookid1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookid1.setForeground(new java.awt.Color(255, 255, 255));
        bookid1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookid1.setText("Book Id");
        bookid1.setBorder(null);
        bookid1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookid1FocusLost(evt);
            }
        });
        bookid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookid1MouseClicked(evt);
            }
        });
        bookid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookid1ActionPerformed(evt);
            }
        });
        returnBookpanel.add(bookid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 180, 30));

        jSeparator11.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator11.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator11.setOpaque(true);
        returnBookpanel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 180, -1));

        userid2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userid2.setForeground(new java.awt.Color(255, 255, 255));
        userid2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userid2.setText("User Id");
        userid2.setBorder(null);
        userid2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userid2FocusLost(evt);
            }
        });
        userid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userid2MouseClicked(evt);
            }
        });
        userid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userid2ActionPerformed(evt);
            }
        });
        returnBookpanel.add(userid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 180, 30));

        jSeparator14.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator14.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator14.setOpaque(true);
        returnBookpanel.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 180, -1));

        issudate1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        issudate1.setForeground(new java.awt.Color(255, 255, 255));
        issudate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        issudate1.setText("Issue Date");
        issudate1.setBorder(null);
        issudate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                issudate1FocusLost(evt);
            }
        });
        issudate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issudate1MouseClicked(evt);
            }
        });
        issudate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issudate1ActionPerformed(evt);
            }
        });
        returnBookpanel.add(issudate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, 30));

        jSeparator15.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator15.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator15.setOpaque(true);
        returnBookpanel.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 180, -1));

        duedate1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        duedate1.setForeground(new java.awt.Color(255, 255, 255));
        duedate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duedate1.setText("Due Date");
        duedate1.setBorder(null);
        duedate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                duedate1FocusLost(evt);
            }
        });
        duedate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duedate1MouseClicked(evt);
            }
        });
        duedate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedate1ActionPerformed(evt);
            }
        });
        returnBookpanel.add(duedate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, 30));

        returnbooksubmit.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        returnbooksubmit.setForeground(new java.awt.Color(0, 204, 209));
        returnbooksubmit.setText("Return Book");
        returnbooksubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnbooksubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbooksubmitActionPerformed(evt);
            }
        });
        returnBookpanel.add(returnbooksubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 140, -1));

        jSeparator16.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator16.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator16.setOpaque(true);
        returnBookpanel.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 180, -1));

        returndateinput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returndateinput.setForeground(new java.awt.Color(255, 255, 255));
        returndateinput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        returndateinput.setText("Return Date");
        returndateinput.setBorder(null);
        returndateinput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                returndateinputFocusLost(evt);
            }
        });
        returndateinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returndateinputMouseClicked(evt);
            }
        });
        returndateinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returndateinputActionPerformed(evt);
            }
        });
        returnBookpanel.add(returndateinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 180, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        returnBookpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        jLabel20.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 51));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginUserIcon/librarybg75.jpg"))); // NOI18N
        jLabel20.setText("Coming Soon............");
        returnBookpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 730, 460));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(booklistpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(returnBookpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 722, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(issuBookpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(afterloginstyle, javax.swing.GroupLayout.PREFERRED_SIZE, 722, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(booklistpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(returnBookpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(issuBookpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(afterloginstyle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BooklistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooklistMouseEntered
        // TODO add your handling code here:
//        jLabel1.setForeground(Color.orange);
    }//GEN-LAST:event_BooklistMouseEntered

    private void BooklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooklistMouseClicked
        // TODO add your handling code here:
        bookLlistTable();
        
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
        }catch(Exception e){
        }
        
        booklistpanel.setVisible(true);
        returnBookpanel.setVisible(false);
        issuBookpanel.setVisible(false);
         afterloginstyle.setVisible(false);
      
        //click time color change
        Booklist.setForeground(Color.orange);
        jLabel2.setForeground(Color.white);
        deletBookbtn.setForeground(Color.white);
        
        
        
        
    }//GEN-LAST:event_BooklistMouseClicked

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        // TODO add your handling code here:
        String searchString=searchText.getText();
        forsearch(searchString);
    }//GEN-LAST:event_searchTextKeyReleased

    private void bookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookidFocusLost
        // TODO add your handling code here:
        String uservalue = bookid.getText().trim();
        if(uservalue.equals("Book  Id") || uservalue.equals("") )
        {
            bookid.setText("Book  Id");
        }
    }//GEN-LAST:event_bookidFocusLost

    private void bookidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookidMouseClicked
        // TODO add your handling code here:
        String uservalue = bookid.getText().trim();
        if(uservalue.equals("Book  Id") || uservalue.equals("") )
        {
            bookid.setText("");
        }
      
    }//GEN-LAST:event_bookidMouseClicked

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookidActionPerformed

    private void useridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_useridFocusLost
        String uservalue = userid.getText().trim();
        if(uservalue.equals("User Id") || uservalue.equals("") )
        {
            userid.setText("User Id");
        }
    }//GEN-LAST:event_useridFocusLost

    private void useridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useridMouseClicked

        String uservalue = userid.getText().trim();
        if(uservalue.equals("User Id") || uservalue.equals("") )
        {
            userid.setText("");
        }

    }//GEN-LAST:event_useridMouseClicked

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void issudateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issudateFocusLost

        String uservalue = issudate.getText().trim();
        if(uservalue.equals("Issue Date") || uservalue.equals("") )
        {
            issudate.setText("Issue Date");
        }

    }//GEN-LAST:event_issudateFocusLost

    private void issudateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issudateMouseClicked

        String uservalue = issudate.getText().trim();
        if(uservalue.equals("Issue Date") || uservalue.equals("") )
        {
            issudate.setText("");
        }

    }//GEN-LAST:event_issudateMouseClicked

    private void issudateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issudateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issudateActionPerformed

    private void duedateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_duedateFocusLost
        String uservalue = duedate.getText().trim();
        if(uservalue.equals("Due Date") || uservalue.equals("") )
        {
            duedate.setText("Due Date");
        }
    }//GEN-LAST:event_duedateFocusLost

    private void duedateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duedateMouseClicked
        String uservalue = duedate.getText().trim();
        if(uservalue.equals("Due Date") || uservalue.equals("") )
        {
            duedate.setText("");
        }
    }//GEN-LAST:event_duedateMouseClicked

    private void duedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedateActionPerformed

    private void jButton_registationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registationBtnActionPerformed
        // TODO add your handling code here:
        try{
           Statement  st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `book_list` WHERE  `Quantity`='"+bookid.getText()+"'");
            
            if(rs.next()){
             ResultSet rs1 = st.executeQuery("SELECT * FROM `registation` WHERE  `userid`='"+userid.getText()+"'");
            
             if(rs1.next()){
             
                  String sql="INSERT INTO `issuebook`(`userid`, `Bookid`, `issuedate`, `duedate`) VALUES (?,?,?,?)";
            p=con.prepareStatement(sql);
            p.setString(1, bookid.getText());
            p.setString(2, userid.getText());
            p.setString(3, issudate.getText());
            p.setString(4, duedate.getText());
           
            if("Book  Id".equals( bookid.getText()) || "User Id".equals( userid.getText()) ||"Issue Date".equals( issudate.getText()) ||"Due Date".equals( duedate.getText())  ){
             JOptionPane.showMessageDialog(this,"Check input!!" );
            }else{
                   p.executeUpdate();
            JOptionPane.showMessageDialog(this,"Issue book Succesfully" );

            bookid.setText("Book  Id");
            userid.setText("User Id");
            issudate.setText("Issue Date");
            duedate.setText("Due Date");
            }
                 
                 
             }else{
             JOptionPane.showMessageDialog(this,"Incorrect User Id" );
             }
             
            }else{
            
            JOptionPane.showMessageDialog(this,"Incorrect Book Id" );
            }
            
            
            
           
         
            

        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton_registationBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        issuBookpanel.setVisible(true);
        booklistpanel.setVisible(false);    
        returnBookpanel.setVisible(false);
         afterloginstyle.setVisible(false);
       
        //click time color change
        Booklist.setForeground(Color.white);
        jLabel2.setForeground(Color.orange);
        deletBookbtn.setForeground(Color.white);
      
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void deletBookbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletBookbtnMouseClicked
      returnBookpanel.setVisible(true);
        issuBookpanel.setVisible(false);
        booklistpanel.setVisible(false);
         afterloginstyle.setVisible(false);
        
        
        
        
        Booklist.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        deletBookbtn.setForeground(Color.orange);
       
    }//GEN-LAST:event_deletBookbtnMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void bookid1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookid1FocusLost
        String uservalue = bookid1.getText().trim();
        if(uservalue.equals("Book Id") || uservalue.equals("") )
        {
            bookid1.setText("Book Id");
        }
    }//GEN-LAST:event_bookid1FocusLost

    private void bookid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookid1MouseClicked
       String uservalue = bookid1.getText().trim();
        if(uservalue.equals("Book Id") || uservalue.equals("") )
        {
            bookid1.setText("");
        }
    }//GEN-LAST:event_bookid1MouseClicked

    private void bookid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookid1ActionPerformed

    private void userid2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userid2FocusLost
       String uservalue = userid2.getText().trim();
        if(uservalue.equals("User Id") || uservalue.equals("") )
        {
            userid2.setText("User Id");
        }
    }//GEN-LAST:event_userid2FocusLost

    private void userid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userid2MouseClicked
        String uservalue = userid2.getText().trim();
        if(uservalue.equals("User Id") || uservalue.equals("") )
        {
            userid2.setText("");
        }
    }//GEN-LAST:event_userid2MouseClicked

    private void userid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userid2ActionPerformed

    private void issudate1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issudate1FocusLost
       String uservalue = issudate1.getText().trim();
        if(uservalue.equals("Issue Date") || uservalue.equals("") )
        {
            issudate1.setText("Issue Date");
        }
    }//GEN-LAST:event_issudate1FocusLost

    private void issudate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issudate1MouseClicked
       String uservalue = issudate1.getText().trim();
        if(uservalue.equals("Issue Date") || uservalue.equals("") )
        {
            issudate1.setText("");
        }
    }//GEN-LAST:event_issudate1MouseClicked

    private void issudate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issudate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issudate1ActionPerformed

    private void duedate1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_duedate1FocusLost
        String uservalue = duedate1.getText().trim();
        if(uservalue.equals("Due Date") || uservalue.equals("") )
        {
            duedate1.setText("Due Date");
        }
    }//GEN-LAST:event_duedate1FocusLost

    private void duedate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duedate1MouseClicked
        String uservalue = duedate1.getText().trim();
        if(uservalue.equals("Due Date") || uservalue.equals("") )
        {
            duedate1.setText("");
        }
    }//GEN-LAST:event_duedate1MouseClicked

    private void duedate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedate1ActionPerformed

    private void returnbooksubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbooksubmitActionPerformed
        
        try{
            
            
            
            
            
            
             Statement  st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `book_list` WHERE  `Quantity`='"+bookid1.getText()+"'");
            
            if(rs.next()){
             ResultSet rs1 = st.executeQuery("SELECT * FROM `registation` WHERE  `userid`='"+userid2.getText()+"'");
            
             if(rs1.next()){
             
                
                 
                   String sql="INSERT INTO `returnbook`(`bookid`, `userid`, `issuedate`, `duedate`, `returndate`) VALUES (?,?,?,?,?)";
            p=con.prepareStatement(sql);
            p.setString(1, bookid1.getText());
            p.setString(2, userid2.getText());
            p.setString(3, issudate1.getText());
            p.setString(4, duedate1.getText());
             p.setString(5, returndateinput.getText());
           
            if("Book  Id".equals( bookid1.getText()) || "User Id".equals( userid2.getText()) ||"Issue Date".equals( issudate1.getText()) ||"Due Date".equals( duedate1.getText()) ||"Return Date".equals( returndateinput.getText()) ){
             JOptionPane.showMessageDialog(this,"Check input!!" );
            }else{
                   p.executeUpdate();
            JOptionPane.showMessageDialog(this,"Issue book Succesfully" );

            bookid1.setText("Book Id");
            userid2.setText("User Id");
            issudate1.setText("Issue Date");
            duedate1.setText("Due Date");
            returndateinput.setText("Return Date");
            }
                 
                 
             }else{
             JOptionPane.showMessageDialog(this,"Incorrect User Id" );
             }
             
            }else{
            
            JOptionPane.showMessageDialog(this,"Incorrect Book Id" );
            }
               

        }catch(Exception e){
        }
        
        
    }//GEN-LAST:event_returnbooksubmitActionPerformed

    private void returndateinputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_returndateinputFocusLost
      String uservalue = returndateinput.getText().trim();
        if(uservalue.equals("Return Date") || uservalue.equals("") )
        {
            returndateinput.setText("Return Date");
        }
    }//GEN-LAST:event_returndateinputFocusLost

    private void returndateinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returndateinputMouseClicked
       String uservalue = returndateinput.getText().trim();
        if(uservalue.equals("Return Date") || uservalue.equals("") )
        {
            returndateinput.setText("");
        }
    }//GEN-LAST:event_returndateinputMouseClicked

    private void returndateinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returndateinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returndateinputActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jButton_registationBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registationBtn2ActionPerformed
        this.setVisible(false);
        new bookPdfUser().setVisible(true);
    }//GEN-LAST:event_jButton_registationBtn2ActionPerformed
  
    public void forsearch(String str){
      DefaultTableModel  model=(DefaultTableModel)tablealldata.getModel();
      TableRowSorter<DefaultTableModel> tablesorter= new TableRowSorter<>(model);
      tablealldata.setRowSorter(tablesorter);
      tablesorter.setRowFilter(RowFilter.regexFilter(str));
    } 
//    public void forsearchuser(String str){
//      DefaultTableModel  model=(DefaultTableModel)tablealldata1.getModel();
//      TableRowSorter<DefaultTableModel> tablesorter= new TableRowSorter<>(model);
//      tablealldata1.setRowSorter(tablesorter);
//      tablesorter.setRowFilter(RowFilter.regexFilter(str));
//    }
    
    
    public void bookLlistTable(){
     
     String sql="SELECT * FROM book_list";

        try{
             p=con.prepareStatement(sql);
             r= p.executeQuery();
            DefaultTableModel model=(DefaultTableModel)tablealldata.getModel();
            model.setRowCount(0);

            while(r.next()){
                model.addRow(new String[]{ r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)});
            }
        }
        catch(Exception e){System.out.println("eroor"+ e.getMessage());}
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Booklist;
    private javax.swing.JPanel afterloginstyle;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookid1;
    private javax.swing.JPanel booklistpanel;
    private javax.swing.JLabel deletBookbtn;
    private javax.swing.JTextField duedate;
    private javax.swing.JTextField duedate1;
    private javax.swing.JPanel issuBookpanel;
    private javax.swing.JTextField issudate;
    private javax.swing.JTextField issudate1;
    private javax.swing.JPanel issueBookbackground;
    private javax.swing.JButton jButton_registationBtn;
    private javax.swing.JButton jButton_registationBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel returnBookpanel;
    private javax.swing.JButton returnbooksubmit;
    private javax.swing.JTextField returndateinput;
    private javax.swing.JTextField searchText;
    private javax.swing.JTable tablealldata;
    private javax.swing.JTextField userid;
    private javax.swing.JTextField userid2;
    // End of variables declaration//GEN-END:variables
}
