/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management;


import java.awt.Desktop;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author rkrakib
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    PreparedStatement p;
    ResultSet r;
    
    public Login() {
        initComponents();
        jTextField_user_name.setBackground(new java.awt.Color(0,0,0,3));
        login_background.setBackground(new java.awt.Color(0,0,0,130));
        jPasswordField_password.setBackground(new java.awt.Color(0,0,0,3));
        jButton3_reg_page.setBackground(new java.awt.Color(0,0,0,3));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rayhankhan = new javax.swing.JLabel();
        rakibmia = new javax.swing.JLabel();
        sadiakhanum = new javax.swing.JLabel();
        hasnahena = new javax.swing.JLabel();
        jTextField_user_name = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox_role_login = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel_login_header = new javax.swing.JLabel();
        login_header_bar = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        login_background = new javax.swing.JPanel();
        jButton3_reg_page = new javax.swing.JButton();
        background_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 209), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 209));

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel2.setText("Library Management");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/book80.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/Online-Library.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.green, java.awt.Color.white, java.awt.Color.orange, java.awt.Color.black));

        jLabel9.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Group Member");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rayhankhan.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        rayhankhan.setForeground(new java.awt.Color(255, 255, 255));
        rayhankhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/facebook-24.png"))); // NOI18N
        rayhankhan.setText("Rayhan Khan");
        rayhankhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rayhankhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rayhankhanMouseClicked(evt);
            }
        });

        rakibmia.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        rakibmia.setForeground(new java.awt.Color(255, 255, 255));
        rakibmia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/github24.png"))); // NOI18N
        rakibmia.setText("Md Rakib Mia");
        rakibmia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rakibmia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rakibmiaMouseClicked(evt);
            }
        });

        sadiakhanum.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        sadiakhanum.setForeground(new java.awt.Color(255, 255, 255));
        sadiakhanum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/facebook-24.png"))); // NOI18N
        sadiakhanum.setText("Sadia Khanum");
        sadiakhanum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sadiakhanum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sadiakhanumMouseClicked(evt);
            }
        });

        hasnahena.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        hasnahena.setForeground(new java.awt.Color(255, 255, 255));
        hasnahena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/facebook-24.png"))); // NOI18N
        hasnahena.setText("Hasna Hena");
        hasnahena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasnahena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hasnahenaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rakibmia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasnahena, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rayhankhan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sadiakhanum, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rayhankhan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rakibmia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sadiakhanum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasnahena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        jTextField_user_name.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        jTextField_user_name.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_user_name.setText("User Name");
        jTextField_user_name.setBorder(null);
        jTextField_user_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_user_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_user_nameFocusLost(evt);
            }
        });
        jTextField_user_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_user_nameMouseClicked(evt);
            }
        });
        jTextField_user_name.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_user_nameInputMethodTextChanged(evt);
            }
        });
        jTextField_user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_nameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 165, 178, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 264, 230, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator2.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 192, 229, -1));

        jComboBox_role_login.setBackground(new java.awt.Color(85, 204, 209));
        jComboBox_role_login.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jComboBox_role_login.setForeground(new java.awt.Color(0, 204, 209));
        jComboBox_role_login.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role", "Author", "Student", "Teacher" }));
        jPanel1.add(jComboBox_role_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 301, 153, 30));

        jButton1.setBackground(new java.awt.Color(52, 91, 123));
        jButton1.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 209));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/login-16.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 229, 36));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/user-16.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 169, 17, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/lock-7-16.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 237, -1, 20));

        jPasswordField_password.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPasswordField_password.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_password.setText("72542");
        jPasswordField_password.setBorder(null);
        jPasswordField_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusLost(evt);
            }
        });
        jPasswordField_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_passwordMouseClicked(evt);
            }
        });
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 237, 178, -1));

        jLabel_login_header.setBackground(new java.awt.Color(51, 255, 255));
        jLabel_login_header.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_login_header.setFont(new java.awt.Font("Unispace", 3, 18)); // NOI18N
        jLabel_login_header.setForeground(new java.awt.Color(0, 204, 209));
        jLabel_login_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_login_header.setText("Login");
        jPanel1.add(jLabel_login_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 115, 35));

        login_header_bar.setBackground(new java.awt.Color(0, 204, 209));
        login_header_bar.setForeground(new java.awt.Color(0, 204, 209));
        login_header_bar.setOpaque(true);
        jPanel1.add(login_header_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 120, -1));

        jLabel8.setBackground(new java.awt.Color(255, 102, 102));
        jLabel8.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 323, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Account:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        login_background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 209)));
        login_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3_reg_page.setBackground(new java.awt.Color(255, 255, 255));
        jButton3_reg_page.setFont(new java.awt.Font("Unispace", 3, 12)); // NOI18N
        jButton3_reg_page.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_reg_page.setText("Registation");
        jButton3_reg_page.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3_reg_page.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3_reg_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_reg_pageActionPerformed(evt);
            }
        });
        login_background.add(jButton3_reg_page, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, 20));

        jPanel1.add(login_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 360, 470));

        background_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/library-background1.jpg"))); // NOI18N
        jPanel1.add(background_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, -2, 440, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_user_nameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_user_nameInputMethodTextChanged
        
    }//GEN-LAST:event_jTextField_user_nameInputMethodTextChanged

    private void jTextField_user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_nameActionPerformed

    }//GEN-LAST:event_jTextField_user_nameActionPerformed

    private void jTextField_user_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_user_nameFocusLost
        // TODO add your handling code here:
         String uservalue = jTextField_user_name.getText().trim().toLowerCase();
        if(uservalue.equals("user name") || uservalue.equals("") )
        { 
            jTextField_user_name.setText("User Name"); 
        }
        
    }//GEN-LAST:event_jTextField_user_nameFocusLost

    private void jTextField_user_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_user_nameFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField_user_nameFocusGained

    private void jTextField_user_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_user_nameMouseClicked
        // TODO add your handling code here:
        String uservalue = jTextField_user_name.getText().trim().toLowerCase();
        if(uservalue.equals("user name") || uservalue.equals("") )
        { 
            jTextField_user_name.setText(""); 
        }
    }//GEN-LAST:event_jTextField_user_nameMouseClicked

    private void jPasswordField_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwordMouseClicked
        // TODO add your handling code here:
        String userpass=String.valueOf(jPasswordField_password.getPassword());
        if(userpass.equals("72542") || userpass.equals(""))
        {
           jPasswordField_password.setText("");
        }
    }//GEN-LAST:event_jPasswordField_passwordMouseClicked

    private void jPasswordField_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusLost
        // TODO add your handling code here:
         String userpass=String.valueOf(jPasswordField_password.getPassword());
        if(userpass.equals("72542") || userpass.equals(""))
        {
           jPasswordField_password.setText("72542");
        }
    }//GEN-LAST:event_jPasswordField_passwordFocusLost

    private void jButton3_reg_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_reg_pageActionPerformed
         // TODO add your handling code here:
         this.setVisible(false);
         new Registation().setVisible(true);
        
    }//GEN-LAST:event_jButton3_reg_pageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="SELECT * FROM `registation` WHERE  `username`=? and `pass`=? and  `Rule`=?";
            p=con.prepareStatement(sql);
            p.setString(1,jTextField_user_name.getText().toLowerCase() );
            p.setString(2,jPasswordField_password.getText());
             String selectvalue=jComboBox_role_login.getSelectedItem().toString();
              p.setString(3,selectvalue);
            r=p.executeQuery();
            
            if(selectvalue=="Author"){
            if(r.next()){
               this.setVisible(false);
               new LoginAuthor().setVisible(true);
              
          }else{
               JOptionPane.showMessageDialog(this," User name or Password or Role Incorrect" ); JOptionPane.showMessageDialog(this," User name or Password or Role Incorrect" ); JOptionPane.showMessageDialog(this," User name or Password or Role Incorrect" ); JOptionPane.showMessageDialog(this, " User name or Password or Role Incorrect");
          }
            
            }else{
            if(r.next()){
               this.setVisible(false);
                 new after_login().setVisible(true);
              
          }else{
               JOptionPane.showMessageDialog(this," User name or Password or Role Incorrect" );
          }
            }
          
            
        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rayhankhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rayhankhanMouseClicked
       Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/profile.php?id=100077042418367"));
        }catch(Exception e){}
    }//GEN-LAST:event_rayhankhanMouseClicked

    private void rakibmiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rakibmiaMouseClicked
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://github.com/rkrakibhasan680"));
        }catch(Exception e){}
    }//GEN-LAST:event_rakibmiaMouseClicked

    private void sadiakhanumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sadiakhanumMouseClicked
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/sadia.khanam.9406"));
        }catch(Exception e){}
       
    }//GEN-LAST:event_sadiakhanumMouseClicked

    private void hasnahenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasnahenaMouseClicked
      Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/hasna.henatori"));
        }catch(Exception e){}
    }//GEN-LAST:event_hasnahenaMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_login;
    private javax.swing.JLabel hasnahena;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3_reg_page;
    private javax.swing.JComboBox<String> jComboBox_role_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_login_header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField_user_name;
    private javax.swing.JPanel login_background;
    private javax.swing.JSeparator login_header_bar;
    private javax.swing.JLabel rakibmia;
    private javax.swing.JLabel rayhankhan;
    private javax.swing.JLabel sadiakhanum;
    // End of variables declaration//GEN-END:variables
}
