/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management;

import java.awt.Color;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

/**
 *
 * @author rkrakib
 */
public class LoginAuthor extends javax.swing.JFrame {
Connection con;
    PreparedStatement p,pp;
    ResultSet r;
    /**
     * Creates new form LoginAuthor
     */
    public LoginAuthor() {
        initComponents();
        afterloginstyle.setVisible(true);
        addbooklistpanel.setVisible(false);
        booklistpanel.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        userinfo.setVisible(false);
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");  
             
            
        }catch(Exception e){
             
        }
        
        
        jPanel13.setBackground(new java.awt.Color(0,0,0,40));
        jPanel14.setBackground(new java.awt.Color(0,0,0,40));
        jPanel3.setBackground(new java.awt.Color(0,0,0,180));
        //addbooklistpanel.setBackground(new java.awt.Color(0,0,0,3));
        Book_name.setBackground(new java.awt.Color(0,0,0,5));
        Book_Author.setBackground(new java.awt.Color(0,0,0,5));
        Book_Edition.setBackground(new java.awt.Color(0,0,0,5));
        Book_Department.setBackground(new java.awt.Color(0,0,0,5));
        Book_status.setBackground(new java.awt.Color(0,0,0,5));
        Book_quantity.setBackground(new java.awt.Color(0,0,0,5));
        searchText1.setBackground(new java.awt.Color(0,0,0,5));
        searchText.setBackground(new java.awt.Color(0,0,0,5));
        jPanel15.setBackground(new java.awt.Color(0,0,0,60));
        
       
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Booklist = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        afterloginstyle = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        booklistpanel = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablealldata = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addbooklistpanel = new javax.swing.JPanel();
        Book_name = new javax.swing.JTextField();
        Book_quantity = new javax.swing.JTextField();
        Book_Author = new javax.swing.JTextField();
        Book_Edition = new javax.swing.JTextField();
        Book_status = new javax.swing.JTextField();
        Book_Department = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jButton_registationBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        userinfo = new javax.swing.JPanel();
        searchText1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablealldata1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(56, 151, 204));
        jPanel1.setForeground(new java.awt.Color(160, 147, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 204, 209));

        Booklist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Booklist.setForeground(new java.awt.Color(255, 255, 255));
        Booklist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/books-24.png"))); // NOI18N
        Booklist.setText("Book list");
        Booklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Booklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooklistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooklistMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Booklist, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(89, 89, 89))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Booklist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 204, 209));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/add-list-24.png"))); // NOI18N
        jLabel2.setText("Add Book");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 204, 209));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/trash-9-24.png"))); // NOI18N
        jLabel3.setText("Delete Book");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 253, -1));

        jPanel4.setBackground(new java.awt.Color(0, 204, 209));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/account-logout-16.png"))); // NOI18N
        jLabel10.setText("Logout");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 30));

        jPanel11.setBackground(new java.awt.Color(0, 204, 209));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/available-updates-24.png"))); // NOI18N
        jLabel4.setText("Update Book");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 245, 250, -1));

        jPanel12.setBackground(new java.awt.Color(0, 204, 209));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/change-user-24.png"))); // NOI18N
        jLabel5.setText("User Info");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 253, -1));

        jLabel6.setBackground(new java.awt.Color(0, 204, 209));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/library-background1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(253, 335));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 2, -1, 460));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 460));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        afterloginstyle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 209));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("City University");
        jPanel15.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 350, 70));

        jLabel19.setBackground(new java.awt.Color(204, 51, 0));
        jLabel19.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, 30));

        afterloginstyle.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/cityuniversity.png"))); // NOI18N
        afterloginstyle.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        booklistpanel.setBackground(new java.awt.Color(204, 204, 204));
        booklistpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchText.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        searchText.setForeground(new java.awt.Color(255, 255, 255));
        searchText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 209)));
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });
        booklistpanel.add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, 30));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablealldata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablealldata.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tablealldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "boook_name", "Author", "Edition", "Status", "Quantity", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablealldata.setCellSelectionEnabled(true);
        tablealldata.setMinimumSize(new java.awt.Dimension(90, 90));
        tablealldata.setRowHeight(30);
        jScrollPane1.setViewportView(tablealldata);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 700, 330));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 209));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Search Record");
        jPanel14.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 140, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/search24.png"))); // NOI18N
        jPanel14.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 30, 50));

        jLabel14.setBackground(new java.awt.Color(204, 51, 0));
        jLabel14.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, -1));

        booklistpanel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgImgAfterLogin/bg-afterLogin.jpg"))); // NOI18N
        booklistpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        addbooklistpanel.setBackground(new java.awt.Color(51, 0, 102));
        addbooklistpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Book_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_name.setForeground(new java.awt.Color(255, 255, 255));
        Book_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_name.setText("Book Name");
        Book_name.setBorder(null);
        Book_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_nameFocusLost(evt);
            }
        });
        Book_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_nameMouseClicked(evt);
            }
        });
        Book_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_nameActionPerformed(evt);
            }
        });
        addbooklistpanel.add(Book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, 30));

        Book_quantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_quantity.setForeground(new java.awt.Color(255, 255, 255));
        Book_quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_quantity.setText("Quantity");
        Book_quantity.setBorder(null);
        Book_quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_quantityFocusLost(evt);
            }
        });
        Book_quantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_quantityMouseClicked(evt);
            }
        });
        Book_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_quantityActionPerformed(evt);
            }
        });
        addbooklistpanel.add(Book_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 180, 30));

        Book_Author.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_Author.setForeground(new java.awt.Color(255, 255, 255));
        Book_Author.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_Author.setText("Author");
        Book_Author.setBorder(null);
        Book_Author.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_AuthorFocusLost(evt);
            }
        });
        Book_Author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_AuthorMouseClicked(evt);
            }
        });
        Book_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_AuthorActionPerformed(evt);
            }
        });
        addbooklistpanel.add(Book_Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 180, 30));

        Book_Edition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_Edition.setForeground(new java.awt.Color(255, 255, 255));
        Book_Edition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_Edition.setText("Edition");
        Book_Edition.setBorder(null);
        Book_Edition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_EditionFocusLost(evt);
            }
        });
        Book_Edition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_EditionMouseClicked(evt);
            }
        });
        Book_Edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_EditionActionPerformed(evt);
            }
        });
        addbooklistpanel.add(Book_Edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, 30));

        Book_status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_status.setForeground(new java.awt.Color(255, 255, 255));
        Book_status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_status.setText("Status");
        Book_status.setBorder(null);
        Book_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_statusFocusLost(evt);
            }
        });
        Book_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_statusMouseClicked(evt);
            }
        });
        Book_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_statusActionPerformed(evt);
            }
        });
        addbooklistpanel.add(Book_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 180, 30));

        Book_Department.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_Department.setForeground(new java.awt.Color(255, 255, 255));
        Book_Department.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Book_Department.setText("Department");
        Book_Department.setBorder(null);
        Book_Department.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Book_DepartmentFocusLost(evt);
            }
        });
        Book_Department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_DepartmentMouseClicked(evt);
            }
        });
        Book_Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_DepartmentActionPerformed(evt);
            }
        });
        addbooklistpanel.add(Book_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 180, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator8.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator8.setOpaque(true);
        addbooklistpanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 180, 2));

        jSeparator9.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator9.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator9.setOpaque(true);
        addbooklistpanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 180, 2));

        jSeparator10.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator10.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator10.setOpaque(true);
        addbooklistpanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 180, 2));

        jSeparator11.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator11.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator11.setOpaque(true);
        addbooklistpanel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 180, 2));

        jSeparator12.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator12.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator12.setOpaque(true);
        addbooklistpanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, 2));

        jSeparator13.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator13.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator13.setOpaque(true);
        addbooklistpanel.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 180, 2));

        jButton_registationBtn.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jButton_registationBtn.setForeground(new java.awt.Color(0, 204, 209));
        jButton_registationBtn.setText("Add book");
        jButton_registationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_registationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registationBtnActionPerformed(evt);
            }
        });
        addbooklistpanel.add(jButton_registationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 140, -1));

        jLabel15.setBackground(new java.awt.Color(204, 51, 0));
        jLabel15.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        addbooklistpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addbooklistpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 470, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/library2.jpg"))); // NOI18N
        addbooklistpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        jPanel6.setBackground(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(50, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        userinfo.setBackground(new java.awt.Color(0, 102, 51));
        userinfo.setPreferredSize(new java.awt.Dimension(710, 460));
        userinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchText1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        searchText1.setForeground(new java.awt.Color(0, 204, 209));
        searchText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 209)));
        searchText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText1ActionPerformed(evt);
            }
        });
        searchText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchText1KeyReleased(evt);
            }
        });
        userinfo.add(searchText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 182, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/search24.png"))); // NOI18N
        userinfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 38, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 209));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Search Record");
        userinfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 161, 30));

        tablealldata1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablealldata1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tablealldata1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User Name", "User Id", "Phone", "Gmail", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablealldata1.setCellSelectionEnabled(true);
        tablealldata1.setMinimumSize(new java.awt.Dimension(90, 90));
        tablealldata1.setRowHeight(30);
        jScrollPane2.setViewportView(tablealldata1);

        userinfo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 680, 270));

        jLabel16.setBackground(new java.awt.Color(204, 51, 0));
        jLabel16.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("X");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        userinfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 20, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAuthoricon/userinformation.jpg"))); // NOI18N
        userinfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(booklistpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(userinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addbooklistpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(afterloginstyle, javax.swing.GroupLayout.PREFERRED_SIZE, 722, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(booklistpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(userinfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addbooklistpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(afterloginstyle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BooklistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooklistMouseEntered
        // TODO add your handling code here:
//        jLabel1.setForeground(Color.orange);
    }//GEN-LAST:event_BooklistMouseEntered

    private void BooklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooklistMouseClicked
        // TODO add your handling code here:
        bookLlistTable();
        booklistpanel.setVisible(true);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        userinfo.setVisible(false);
        addbooklistpanel.setVisible(false);
        //click time color change
        Booklist.setForeground(Color.orange);
        jLabel2.setForeground(Color.white);
        jLabel3.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel5.setForeground(Color.white);
        
        
        
    }//GEN-LAST:event_BooklistMouseClicked

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        // TODO add your handling code here:
        String searchString=searchText.getText();
        forsearch(searchString);
    }//GEN-LAST:event_searchTextKeyReleased

    private void Book_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_nameFocusLost
        // TODO add your handling code here:
        String uservalue = Book_name.getText().trim().toLowerCase();
        if(uservalue.equals("book name") || uservalue.equals("") )
        {
            Book_name.setText("Book Name");
        }
    }//GEN-LAST:event_Book_nameFocusLost

    private void Book_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_nameMouseClicked
        // TODO add your handling code here:
        String uservalue = Book_name.getText().trim().toLowerCase();
        if(uservalue.equals("book name") || uservalue.equals("") )
        {
            Book_name.setText("");
        }
      
    }//GEN-LAST:event_Book_nameMouseClicked

    private void Book_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_nameActionPerformed

    private void Book_AuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_AuthorFocusLost
        String uservalue = Book_Author.getText().trim().toLowerCase();
        if(uservalue.equals("author") || uservalue.equals("") )
        {
            Book_Author.setText("Author");
        }
    }//GEN-LAST:event_Book_AuthorFocusLost

    private void Book_AuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_AuthorMouseClicked

        String uservalue = Book_Author.getText().trim().toLowerCase();
        if(uservalue.equals("author") || uservalue.equals("") )
        {
            Book_Author.setText("");
        }

    }//GEN-LAST:event_Book_AuthorMouseClicked

    private void Book_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_AuthorActionPerformed

    private void Book_EditionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_EditionFocusLost

        String uservalue = Book_Edition.getText().trim().toLowerCase();
        if(uservalue.equals("edition") || uservalue.equals("") )
        {
            Book_Edition.setText("Edition");
        }

    }//GEN-LAST:event_Book_EditionFocusLost

    private void Book_EditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_EditionMouseClicked

        String uservalue = Book_Edition.getText().trim().toLowerCase();
        if(uservalue.equals("edition") || uservalue.equals("") )
        {
            Book_Edition.setText("");
        }

    }//GEN-LAST:event_Book_EditionMouseClicked

    private void Book_EditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_EditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_EditionActionPerformed

    private void Book_statusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_statusFocusLost
        String uservalue = Book_status.getText().trim().toLowerCase();
        if(uservalue.equals("status") || uservalue.equals("") )
        {
            Book_status.setText("Status");
        }
    }//GEN-LAST:event_Book_statusFocusLost

    private void Book_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_statusMouseClicked

        String uservalue = Book_status.getText().trim().toLowerCase();
        if(uservalue.equals("status") || uservalue.equals("") )
        {
            Book_status.setText("");
        }

    }//GEN-LAST:event_Book_statusMouseClicked

    private void Book_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_statusActionPerformed

    private void Book_quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_quantityFocusLost

        String uservalue = Book_quantity.getText().trim().toLowerCase();
        if(uservalue.equals("quantity") || uservalue.equals("") )
        {
            Book_quantity.setText("Quantity");
        }
    }//GEN-LAST:event_Book_quantityFocusLost

    private void Book_quantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_quantityMouseClicked

        String uservalue = Book_quantity.getText().trim().toLowerCase();
        if(uservalue.equals("quantity") || uservalue.equals("") )
        {
            Book_quantity.setText("");
        }

    }//GEN-LAST:event_Book_quantityMouseClicked

    private void Book_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_quantityActionPerformed

    private void Book_DepartmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Book_DepartmentFocusLost
        String uservalue = Book_Department.getText().trim().toLowerCase();
        if(uservalue.equals("department") || uservalue.equals("") )
        {
            Book_Department.setText("Department");
        }
    }//GEN-LAST:event_Book_DepartmentFocusLost

    private void Book_DepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_DepartmentMouseClicked
        String uservalue = Book_Department.getText().trim().toLowerCase();
        if(uservalue.equals("department") || uservalue.equals("") )
        {
            Book_Department.setText("");
        }
    }//GEN-LAST:event_Book_DepartmentMouseClicked

    private void Book_DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_DepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_DepartmentActionPerformed

    private void jButton_registationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registationBtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="INSERT INTO `book_list`(`boook_name`, `Author`, `Edition`, `Status`, `Quantity`, `Department`) VALUES (?,?,?,?,?,?)";
            p=con.prepareStatement(sql);
            p.setString(1, Book_name.getText());
            p.setString(2, Book_Author.getText());
            p.setString(3, Book_Edition.getText());
            p.setString(4, Book_status.getText());
            p.setString(5, Book_quantity.getText());
            p.setString(6, Book_Department.getText());
            p.executeUpdate();
            JOptionPane.showMessageDialog(this," Add book Succesfull" );

            Book_name.setText("Book Name");
            Book_Author.setText("Author");
            Book_Edition.setText("Edition");
            Book_status.setText("Status");
            Book_quantity.setText("Quantity");
            Book_Department.setText("Department");

        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton_registationBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        addbooklistpanel.setVisible(true);
        booklistpanel.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        userinfo.setVisible(false);
        //click time color change
        Booklist.setForeground(Color.white);
        jLabel2.setForeground(Color.orange);
        jLabel3.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel5.setForeground(Color.white);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        userinfo.setVisible(true);
        addbooklistpanel.setVisible(false);
        booklistpanel.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
         //click time color change
        Booklist.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        jLabel3.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel5.setForeground(Color.orange);
         String sql="SELECT * FROM registation";
       
        try{      
          p=con.prepareStatement(sql); 
         ResultSet rr= p.executeQuery();
          DefaultTableModel model=(DefaultTableModel)tablealldata1.getModel();
          model.setRowCount(0);
          
          while(rr.next()){
          model.addRow(new String[]{ rr.getString(1),rr.getString(2),rr.getString(3),rr.getString(4),rr.getString(5),rr.getString(6)});
          }
        }
        catch(Exception e){System.out.println("eroor"+ e.getMessage());}
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void searchText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_searchText1ActionPerformed

    private void searchText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText1KeyReleased
        String searchString=searchText1.getText();
        forsearchuser(searchString);
       
    }//GEN-LAST:event_searchText1KeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       //click time color change
        Booklist.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        jLabel3.setForeground(Color.orange);
        jLabel4.setForeground(Color.white);
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       //click time color change
        Booklist.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        jLabel3.setForeground(Color.white);
        jLabel4.setForeground(Color.orange);
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked
  
    public void forsearch(String str){
      DefaultTableModel  model=(DefaultTableModel)tablealldata.getModel();
      TableRowSorter<DefaultTableModel> tablesorter= new TableRowSorter<>(model);
      tablealldata.setRowSorter(tablesorter);
      tablesorter.setRowFilter(RowFilter.regexFilter(str));
    } 
    public void forsearchuser(String str){
      DefaultTableModel  model=(DefaultTableModel)tablealldata1.getModel();
      TableRowSorter<DefaultTableModel> tablesorter= new TableRowSorter<>(model);
      tablealldata1.setRowSorter(tablesorter);
      tablesorter.setRowFilter(RowFilter.regexFilter(str));
    }
    
    
    public void bookLlistTable(){
     
     String sql="SELECT * FROM book_list";

        try{
             p=con.prepareStatement(sql);
             r= p.executeQuery();
            DefaultTableModel model=(DefaultTableModel)tablealldata.getModel();
            model.setRowCount(0);

            while(r.next()){
                model.addRow(new String[]{ r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)});
            }
        }
        catch(Exception e){System.out.println("eroor"+ e.getMessage());}
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAuthor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Book_Author;
    private javax.swing.JTextField Book_Department;
    private javax.swing.JTextField Book_Edition;
    private javax.swing.JTextField Book_name;
    private javax.swing.JTextField Book_quantity;
    private javax.swing.JTextField Book_status;
    private javax.swing.JLabel Booklist;
    private javax.swing.JPanel addbooklistpanel;
    private javax.swing.JPanel afterloginstyle;
    private javax.swing.JPanel booklistpanel;
    private javax.swing.JButton jButton_registationBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField searchText1;
    private javax.swing.JTable tablealldata;
    private javax.swing.JTable tablealldata1;
    private javax.swing.JPanel userinfo;
    // End of variables declaration//GEN-END:variables
}
