/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author rkrakib
 */
public class Registation extends javax.swing.JFrame {

    /**
     * Creates new form Registation
     */
    PreparedStatement p;
    ResultSet r;
    
    
    
    
    public Registation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_main_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField_user_name_reg = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField_user_id_reg = new javax.swing.JTextField();
        jTextField_user_phone_reg = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField_user_mail = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jPasswordField_reg_pass = new javax.swing.JPasswordField();
        jComboBox1_role = new javax.swing.JComboBox<>();
        jButton_registationBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_main_panel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 209)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/book80.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Library Management");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/Online-Library.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.green, java.awt.Color.white, java.awt.Color.orange, java.awt.Color.black));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(84, 84, 84))
        );

        jPanel_header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 209));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registation");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(255, 102, 102));
        jLabel8.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator4.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator4.setOpaque(true);

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jTextField_user_name_reg.setText("User Name");
        jTextField_user_name_reg.setBorder(null);
        jTextField_user_name_reg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_user_name_regFocusLost(evt);
            }
        });
        jTextField_user_name_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_user_name_regMouseClicked(evt);
            }
        });
        jTextField_user_name_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_name_regActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator1.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator1.setOpaque(true);

        jSeparator2.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator2.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator2.setOpaque(true);

        jTextField_user_id_reg.setText("User Id");
        jTextField_user_id_reg.setBorder(null);
        jTextField_user_id_reg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_user_id_regFocusLost(evt);
            }
        });
        jTextField_user_id_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_user_id_regMouseClicked(evt);
            }
        });
        jTextField_user_id_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_id_regActionPerformed(evt);
            }
        });

        jTextField_user_phone_reg.setText("Phone");
        jTextField_user_phone_reg.setBorder(null);
        jTextField_user_phone_reg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_user_phone_regFocusLost(evt);
            }
        });
        jTextField_user_phone_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_user_phone_regMouseClicked(evt);
            }
        });
        jTextField_user_phone_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_phone_regActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator5.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator5.setOpaque(true);

        jSeparator6.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator6.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator6.setOpaque(true);

        jTextField_user_mail.setText("Gmail");
        jTextField_user_mail.setBorder(null);
        jTextField_user_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_user_mailFocusLost(evt);
            }
        });
        jTextField_user_mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_user_mailMouseClicked(evt);
            }
        });
        jTextField_user_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_mailActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 204, 209));
        jSeparator7.setForeground(new java.awt.Color(0, 204, 209));
        jSeparator7.setOpaque(true);

        jPasswordField_reg_pass.setText("72542");
        jPasswordField_reg_pass.setBorder(null);
        jPasswordField_reg_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_reg_passFocusLost(evt);
            }
        });
        jPasswordField_reg_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_reg_passMouseClicked(evt);
            }
        });

        jComboBox1_role.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jComboBox1_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role", "Authore", "Student", "Teacher" }));

        jButton_registationBtn.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jButton_registationBtn.setForeground(new java.awt.Color(0, 204, 209));
        jButton_registationBtn.setText("Registation");
        jButton_registationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_registationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registationBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/student-16.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/user-16.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/phone-42-16.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/gmail-login-16.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management/icon/lock-7-16.png"))); // NOI18N

        jButton2.setFont(new java.awt.Font("Unispace", 2, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Login Page");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_main_panelLayout = new javax.swing.GroupLayout(jPanel_main_panel);
        jPanel_main_panel.setLayout(jPanel_main_panelLayout);
        jPanel_main_panelLayout.setHorizontalGroup(
            jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_main_panelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_main_panelLayout.createSequentialGroup()
                        .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_main_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_main_panelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_user_name_reg)
                                    .addComponent(jSeparator1)
                                    .addComponent(jSeparator2)
                                    .addComponent(jTextField_user_id_reg, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(jTextField_user_phone_reg, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(jSeparator5)
                                    .addComponent(jSeparator6)
                                    .addComponent(jTextField_user_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(jSeparator7)
                                    .addComponent(jPasswordField_reg_pass)
                                    .addComponent(jButton_registationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1_role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel_main_panelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_main_panelLayout.setVerticalGroup(
            jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_user_name_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_user_id_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_user_phone_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_user_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_main_panelLayout.createSequentialGroup()
                        .addComponent(jPasswordField_reg_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1_role, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_registationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTextField_user_name_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_name_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user_name_regActionPerformed

    private void jTextField_user_name_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_user_name_regMouseClicked
        // TODO add your handling code here:
         String uservalue = jTextField_user_name_reg.getText().trim().toLowerCase();
        if(uservalue.equals("user name") || uservalue.equals("") )
        { 
            jTextField_user_name_reg.setText(""); 
        }
    }//GEN-LAST:event_jTextField_user_name_regMouseClicked

    private void jTextField_user_id_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_id_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user_id_regActionPerformed

    private void jTextField_user_id_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_user_id_regMouseClicked
        // TODO add your handling code here:
         String uservalue = jTextField_user_id_reg.getText().trim().toLowerCase();
        if(uservalue.equals("user id") || uservalue.equals("") )
        { 
            jTextField_user_id_reg.setText(""); 
        }
    }//GEN-LAST:event_jTextField_user_id_regMouseClicked

    private void jTextField_user_phone_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_phone_regActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_user_phone_regActionPerformed

    private void jTextField_user_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user_mailActionPerformed

    private void jTextField_user_phone_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_user_phone_regMouseClicked
        // TODO add your handling code here:
         String uservalue = jTextField_user_phone_reg.getText().trim().toLowerCase();
        if(uservalue.equals("phone") || uservalue.equals("") )
        { 
            jTextField_user_phone_reg.setText(""); 
        }
    }//GEN-LAST:event_jTextField_user_phone_regMouseClicked

    private void jTextField_user_mailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_user_mailMouseClicked
        // TODO add your handling code here:
        String uservalue = jTextField_user_mail.getText().trim().toLowerCase();
        if(uservalue.equals("gmail") || uservalue.equals("") )
        { 
            jTextField_user_mail.setText(""); 
        }
    }//GEN-LAST:event_jTextField_user_mailMouseClicked

    private void jPasswordField_reg_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_reg_passMouseClicked
        // TODO add your handling code here:
        String userpass=String.valueOf(jPasswordField_reg_pass.getPassword());
        if(userpass.equals("72542") || userpass.equals(""))
        {
           jPasswordField_reg_pass.setText("");
        }
    }//GEN-LAST:event_jPasswordField_reg_passMouseClicked

    private void jPasswordField_reg_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_reg_passFocusLost
        // TODO add your handling code here:
         String userpass=String.valueOf(jPasswordField_reg_pass.getPassword());
        if(userpass.equals("72542") || userpass.equals(""))
        {
           jPasswordField_reg_pass.setText("72542");
        }
    }//GEN-LAST:event_jPasswordField_reg_passFocusLost

    private void jTextField_user_name_regFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_user_name_regFocusLost
        // TODO add your handling code here:
         String uservalue = jTextField_user_name_reg.getText().trim().toLowerCase();
        if(uservalue.equals("user name") || uservalue.equals("") )
        { 
            jTextField_user_name_reg.setText("User Name"); 
        }
    }//GEN-LAST:event_jTextField_user_name_regFocusLost

    private void jTextField_user_id_regFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_user_id_regFocusLost
        // TODO add your handling code here:
         String uservalue = jTextField_user_id_reg.getText().trim().toLowerCase();
        if(uservalue.equals("user id") || uservalue.equals("") )
        { 
            jTextField_user_id_reg.setText("User Id"); 
        }
    }//GEN-LAST:event_jTextField_user_id_regFocusLost

    private void jTextField_user_phone_regFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_user_phone_regFocusLost
        // TODO add your handling code here:
          String uservalue = jTextField_user_phone_reg.getText().trim().toLowerCase();
        if(uservalue.equals("phone") || uservalue.equals("") )
        { 
            jTextField_user_phone_reg.setText("phone"); 
        }
    }//GEN-LAST:event_jTextField_user_phone_regFocusLost

    private void jTextField_user_mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_user_mailFocusLost
        // TODO add your handling code here:
         String uservalue = jTextField_user_mail.getText().trim().toLowerCase();
        if(uservalue.equals("gmail") || uservalue.equals("") )
        { 
            jTextField_user_mail.setText("Gmail"); 
        }
    }//GEN-LAST:event_jTextField_user_mailFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_registationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registationBtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
            String sql="INSERT INTO `registation`(`username`, `userid`, `phone`, `gmail`, `pass`) VALUES (?,?,?,?,?)";
            p=con.prepareStatement(sql);
            p.setString(1, jTextField_user_name_reg.getText());
           p.setString(2, jTextField_user_id_reg.getText());
           p.setString(3, jTextField_user_phone_reg.getText());
            p.setString(4, jTextField_user_mail.getText());
           
            p.setString(5, jPasswordField_reg_pass.getText());
            p.executeUpdate();
           JOptionPane.showMessageDialog(this," is succesfully registation" );
            
            
        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton_registationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_registationBtn;
    private javax.swing.JComboBox<String> jComboBox1_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_main_panel;
    private javax.swing.JPasswordField jPasswordField_reg_pass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField_user_id_reg;
    private javax.swing.JTextField jTextField_user_mail;
    private javax.swing.JTextField jTextField_user_name_reg;
    private javax.swing.JTextField jTextField_user_phone_reg;
    // End of variables declaration//GEN-END:variables
}
